<a href="https://colab.research.google.com/github/MINJI-95236/2024_data-science/blob/main/0423_numpy_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 데이터를 분석하는 데 필요한 패키지인 numpy를 불러와주세요.

In [ ]:
import numpy as np

# 아래 출력 결과와 동일한 배열을 생성하고, 이를 'z' 변수에 할당하세요. 그리고 print()를 이용하여 출력하세요.

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#아래 출력 결과와 동일한 배열을 생성하고, 이를 o(소문자 알파벳) 변수에 할당하세요. 그리고 print()를 이용하여 출력하세요.

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# 아래 출력 결과와 동일한 배열을 생성하고, 이를 'f' 변수에 할당하세요. 그리고 print()를 이용하여 출력하세요.

[[8 8]
 [8 8]
 [8 8]
 [8 8]]


# 4부터 11(포함)까지의 모든 연속 정수를 포함하는 1차원 배열을 생성하고, 이를 'arr_1' 변수에 할당하세요. 그리고 print()를 이용하여 출력하세요.

[ 4  5  6  7  8  9 10 11]


#위에서 생성한 1차원 배열 arr 을 4행 2열의 2차원 배열로 형태를 변경하여 반환하세요. 2차원 배열은 변수 arr_2 에 할당하세요. 그리고 print()를 이용하여 출력하세요.

[[ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


# 2부터 시작하여 10(포함)까지 2씩 증가하는 원소로 이루어지는 1차원 배열을 생성하고, 이를 변수 a에 할당하세요. 그리고 print()를 이용하여 출력하세요.

[ 2  4  6  8 10]


# 생성한 배열  a에서 마지막 원소를 인덱스를 사용하여 출력하세요.

10


# 아래 출력 결과는 1차원 배열 a를 슬라이싱한 결과입니다. 동일한 결과를 얻을 수 있도록 코드를 작성하세요.

[ 8 10]


# 6부터 시작하여 29(포함)까지의 모든 연속 정수를 포함하는 2차원 배열을 생성하고, 이를 변수 b에 할당하세요. 그리고 print()를 이용하여 출력하세요.

* 조건: arange( )와 reshape( )를 사용해야합니다.

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]


# 아래 출력 결과는 생성된 2차원 배열 b를 슬라이싱한 결과입니다. 동일한 결과를 얻을 수 있도록 코드를 작성하세요.

[[11 12]
 [15 16]]
